#!/usr/bin/env bash
# Build .deb package for gsbs-client using nfpm.
# Usage: ./script/packaging/linux/build-deb.sh OUT_DIR VERSION [ARCH]
#   ARCH: amd64 (default) or arm64
set -euo pipefail

OUT_DIR="${1:-dist}"
VERSION="${2:-}"
ARCH="${3:-amd64}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
FLATPAK_DIR="${ROOT}/flatpak"

if [ -z "$VERSION" ]; then
  echo "Usage: $0 OUT_DIR VERSION [ARCH]" >&2
  exit 1
fi

VERSION_VALUE="${VERSION#v}"
CLIENT_BIN="${ROOT}/${OUT_DIR}/gsbs-client-linux-${ARCH}"
if [ ! -f "$CLIENT_BIN" ]; then
  echo "Missing client binary: $CLIENT_BIN" >&2
  exit 1
fi

WORK="${ROOT}/${OUT_DIR}/deb-work"
rm -rf "$WORK"
mkdir -p "$WORK/icons"

# Binary (neutral staged name; nfpm maps it to /usr/bin/gsbs-client).
cp "$CLIENT_BIN" "$WORK/gsbs-client"

# Canonical desktop + AppStream metadata (shared with Flatpak/AppImage).
cp "$FLATPAK_DIR/io.github.dlommm.GSBS.desktop" "$WORK/"
cp "$FLATPAK_DIR/io.github.dlommm.GSBS.metainfo.xml" "$WORK/"

# Multi-size hicolor icons (generated by cmd/gen-branding into flatpak/icons/).
for s in 16 32 48 64 128 256; do
  cp "$FLATPAK_DIR/icons/${s}x${s}/io.github.dlommm.GSBS.png" "$WORK/icons/${s}.png"
done

# Maintainer scripts + nfpm config.
cp "$SCRIPT_DIR/postinstall.sh" "$WORK/"
cp "$SCRIPT_DIR/postremove.sh" "$WORK/"
cp "$SCRIPT_DIR/nfpm.yaml" "$WORK/"

export VERSION="$VERSION_VALUE"
export ARCH
cd "$WORK"
nfpm pkg \
  --config nfpm.yaml \
  --packager deb \
  --target "${ROOT}/${OUT_DIR}"

# nfpm names output deterministically as ${name}_${version}_${arch}.deb.
EXPECTED="gsbs-client_${VERSION_VALUE}_${ARCH}.deb"
if [ ! -f "${ROOT}/${OUT_DIR}/${EXPECTED}" ]; then
  echo "Expected ${OUT_DIR}/${EXPECTED} not produced by nfpm" >&2
  ls -la "${ROOT}/${OUT_DIR}/"*.deb 2>/dev/null || true
  exit 1
fi
echo "Built ${OUT_DIR}/${EXPECTED}"
