#!/usr/bin/env bash
# Build AppImage for gsbs-client using linuxdeploy.
# Usage: ./script/packaging/linux/build-appimage.sh OUT_DIR VERSION [ARCH]
#   ARCH: amd64 (default) or arm64
set -euo pipefail

OUT_DIR="${1:-dist}"
VERSION="${2:-}"
ARCH="${3:-amd64}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
FLATPAK_DIR="${ROOT}/flatpak"

if [ -z "$VERSION" ]; then
  echo "Usage: $0 OUT_DIR VERSION [ARCH]" >&2
  exit 1
fi
if ! command -v file >/dev/null 2>&1; then
  echo "file(1) is required for appimagetool (e.g. apt install file)" >&2
  exit 1
fi

# Map Go arch -> AppImage/uname arch.
case "$ARCH" in
  amd64) IMG_ARCH=x86_64 ;;
  arm64) IMG_ARCH=aarch64 ;;
  *) echo "Unsupported ARCH: $ARCH" >&2; exit 1 ;;
esac

VERSION_VALUE="${VERSION#v}"
CLIENT_BIN="${ROOT}/${OUT_DIR}/gsbs-client-linux-${ARCH}"
if [ ! -f "$CLIENT_BIN" ]; then
  echo "Missing client binary: $CLIENT_BIN" >&2
  exit 1
fi

APPDIR="${ROOT}/${OUT_DIR}/AppDir"
rm -rf "$APPDIR"
mkdir -p "$APPDIR/usr/bin" "$APPDIR/usr/share/applications" "$APPDIR/usr/share/metainfo"

cp "$CLIENT_BIN" "$APPDIR/usr/bin/gsbs-client"
chmod +x "$APPDIR/usr/bin/gsbs-client"

# Canonical desktop + AppStream metadata (shared with Flatpak/.deb).
cp "$FLATPAK_DIR/io.github.dlommm.GSBS.desktop" "$APPDIR/usr/share/applications/"
cp "$FLATPAK_DIR/io.github.dlommm.GSBS.metainfo.xml" "$APPDIR/usr/share/metainfo/"

# Multi-size hicolor icons (generated by cmd/gen-branding into flatpak/icons/).
for s in 16 32 48 64 128 256; do
  dir="$APPDIR/usr/share/icons/hicolor/${s}x${s}/apps"
  mkdir -p "$dir"
  cp "$FLATPAK_DIR/icons/${s}x${s}/io.github.dlommm.GSBS.png" "$dir/io.github.dlommm.GSBS.png"
done
MAIN_ICON="$APPDIR/usr/share/icons/hicolor/256x256/apps/io.github.dlommm.GSBS.png"

cp "$SCRIPT_DIR/AppRun" "$APPDIR/AppRun"
chmod +x "$APPDIR/AppRun"

DEPLOY_DIR="${ROOT}/${OUT_DIR}"
LINUXDEPLOY="${DEPLOY_DIR}/linuxdeploy-${IMG_ARCH}.AppImage"
PLUGIN="${DEPLOY_DIR}/linuxdeploy-plugin-appimage-${IMG_ARCH}.AppImage"

if [ ! -f "$LINUXDEPLOY" ]; then
  curl -fsSL -o "$LINUXDEPLOY" "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-${IMG_ARCH}.AppImage"
  chmod +x "$LINUXDEPLOY"
fi
if [ ! -f "$PLUGIN" ]; then
  curl -fsSL -o "$PLUGIN" "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-${IMG_ARCH}.AppImage"
  chmod +x "$PLUGIN"
fi

OUT_FILE="gsbs-client-${VERSION_VALUE}-${IMG_ARCH}.AppImage"
export ARCH="$IMG_ARCH"
export VERSION="$VERSION_VALUE"
# linuxdeploy-plugin-appimage honors OUTPUT for an exact output filename.
export OUTPUT="$OUT_FILE"
# CI and containerized runners often lack FUSE; extract-and-run avoids fusermount.
export APPIMAGE_EXTRACT_AND_RUN=1
cd "$DEPLOY_DIR"

"$LINUXDEPLOY" \
  --appdir "$APPDIR" \
  --desktop-file "$APPDIR/usr/share/applications/io.github.dlommm.GSBS.desktop" \
  --icon-file "$MAIN_ICON" \
  --output appimage

if [ ! -f "$OUT_FILE" ]; then
  echo "AppImage output not found in ${DEPLOY_DIR}" >&2
  ls -la ./*.AppImage 2>/dev/null || true
  exit 1
fi
echo "Built ${DEPLOY_DIR}/${OUT_FILE}"
